### ISSUE TITLE
Deinterlace causes crash

### ISSUE THREAD

**Issue by ValdikSS** [xylosper/cmplayer#49]
I have a DVD .VOB and when I try to set deinterlace option to auto, cmplayer crashes. If deinterlace option was set to auto before opening this file, deinterlacing works fine.

File: http://yadi.sk/d/7HH07wenJkSX7

Backtrace:

```
valdikss@valaptop ~/a % gdb  --args /usr/bin/cmplayer --open /home/valdikss/ippatsu/VTS_01_1.VOB
GNU gdb (GDB) 7.7
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/cmplayer...done.
(gdb) r
Starting program: /usr/bin/cmplayer --open /home/valdikss/ippatsu/VTS_01_1.VOB
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
warning: File "/usr/lib/libstdc++.so.6.0.19-gdb.py" auto-loading has been declined by your 'auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /usr/lib/libstdc++.so.6.0.19-gdb.py
line to your configuration file "/home/valdikss/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/valdikss/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
[New Thread 0x7ffff272d700 (LWP 15018)]
"Qt Warning - invalid keysym: dead_actute" 
[OpenGL] Check OpenGL stuffs.
[OpenGL] Version: 3.0
[OpenGL] FBO texture format: GL_RGBA16
[OpenGL] Available extensions: GL_ARB_texture_rg, GL_ARB_texture_float, GL_KHR_debug, GL_MESA_ycbcr_texture, GL_ARB_framebuffer_object
libva info: VA-API version 0.34.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_34
libva info: va_openDriver() returns 0
[New Thread 0x7fffeba8c700 (LWP 15019)]
Initialize engine 
[New Thread 0x7fffeadc2700 (LWP 15020)]
[New Thread 0x7fffea5c1700 (LWP 15021)]
Make connections 
Recover states 
Try system tray icon 
Create system tray icon 
[New Thread 0x7fffe8882700 (LWP 15022)]
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
[New Thread 0x7fffd7f3e700 (LWP 15023)]

Program received signal SIGSEGV, Segmentation fault.
0x000000300eb19b5d in QOpenGLShaderProgram::uniformLocation(char const*) const () from /usr/lib/libQt5Gui.so.5
(gdb) bt
#0  0x000000300eb19b5d in QOpenGLShaderProgram::uniformLocation(char const*) const () from /usr/lib/libQt5Gui.so.5
#1  0x000000000056cb1b in VideoFrameShader::updateShader() ()
#2  0x000000000056efb1 in VideoFrameShader::upload(VideoFrame&) ()
#3  0x000000000052a40b in VideoRendererItem::prepare(QSGGeometryNode*) ()
#4  0x000000000052cd5d in TextureRendererItem::updatePaintNode(QSGNode*, QQuickItem::UpdatePaintNodeData*) ()
#5  0x0000003007f715e8 in QQuickWindowPrivate::updateDirtyNode(QQuickItem*) () from /usr/lib/libQt5Quick.so.5
#6  0x0000003007f722b4 in QQuickWindowPrivate::updateDirtyNodes() () from /usr/lib/libQt5Quick.so.5
#7  0x0000003007f7231b in QQuickWindowPrivate::syncSceneGraph() () from /usr/lib/libQt5Quick.so.5
#8  0x0000003007f502d4 in ?? () from /usr/lib/libQt5Quick.so.5
#9  0x0000003007f50ae5 in ?? () from /usr/lib/libQt5Quick.so.5
#10 0x0000003017b3abec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#11 0x0000003017b3fdb6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff7b93aad in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#13 0x00007ffff7bdff35 in QTimerInfoList::activateTimers() () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff7be03f1 in ?? () from /usr/lib/libQt5Core.so.5
#15 0x0000003003248296 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#16 0x00000030032485e8 in ?? () from /usr/lib/libglib-2.0.so.0
#17 0x000000300324868c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#18 0x00007ffff7be071c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#19 0x00007ffff7b927eb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff7b98f61 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#21 0x000000000043e521 in main ()
```

**Comment by xylosper** [comment]
I think this is fixed in recent source, too.
If still occurs, please let me know to reopen this issue.
Thank you.

**Comment by ValdikSS** [comment]
OSD always prints that deinterlacer is activated on interlaced content, even if it turned off in menu.

**Comment by xylosper** [comment]
Fixed. Thank you.
